### ISSUE TITLE
Fix inclusion of ObjectStoreEnvironmentBean default constructor

### ISSUE THREAD

**Issue by nmcl** [nmcl/scratch#23]
native-image -jar AITBasic.jar -H:IncludeResources='./com/arjuna/ats/arjuna/common/ObjectStoreEnvironmentBean.class' -Dcom.arjuna.ats.arjuna.common.propertiesFile=abs:///Users/marklittle/github/scratch/graalvm/transactions/arjunacore/etc/jbossts-properties.xml
watchmen:arjunacore marklittle$ ls -l ./com/arjuna/ats/arjuna/common/ObjectStoreEnvironmentBean.class 

... still gives ...

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at com.oracle.svm.reflect.proxies.Proxy_7_AITBasic_main.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:173)
Caused by: java.lang.RuntimeException: java.lang.InstantiationException: Type `com.arjuna.ats.arjuna.common.ObjectStoreEnvironmentBean` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Throwable.<init>(Throwable.java:310)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
	at com.arjuna.common.internal.util.propertyservice.BeanPopulator.getNamedInstance(BeanPopulator.java:90)
	at com.arjuna.common.internal.util.propertyservice.BeanPopulator.getNamedInstance(BeanPopulator.java:66)
	at com.arjuna.ats.arjuna.objectstore.StoreManager.initStore(StoreManager.java:146)
	at com.arjuna.ats.arjuna.objectstore.StoreManager.setupStore(StoreManager.java:136)
	at com.arjuna.ats.arjuna.StateManager.setupStore(StateManager.java:1144)
	at com.arjuna.ats.arjuna.StateManager.setupStore(StateManager.java:1078)
	at com.arjuna.ats.arjuna.StateManager.activate(StateManager.java:258)
	at com.arjuna.ats.arjuna.StateManager.activate(StateManager.java:168)
	at BasicObject.activate(AITBasic.java:129)
	at BasicObject.<init>(AITBasic.java:72)
	at AITBasic.main(AITBasic.java:51)
	... 3 more
Caused by: java.lang.InstantiationException: Type `com.arjuna.ats.arjuna.common.ObjectStoreEnvironmentBean` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:56)
	at java.lang.InstantiationException.<init>(InstantiationException.java:63)
	at com.oracle.svm.core.hub.DynamicHub.newInstance(DynamicHub.java:592)
	at com.arjuna.common.internal.util.propertyservice.BeanPopulator.getNamedInstance(BeanPopulator.java:82)

Going to hack around it for now.

**Comment by nmcl** [comment]
Hacked Narayana ...

private static final ObjectStoreAPI initStore(String name)
    {
	//ObjectStoreEnvironmentBean storeEnvBean = BeanPopulator.getNamedInstance(ObjectStoreEnvironmentBean.class, name);
	ObjectStoreEnvironmentBean storeEnvBean = new ObjectStoreEnvironmentBean();

**Comment by nmcl** [comment]
AltStoreTest ...

@Test
    public void test() throws IOException, ObjectStoreException
    {
        final OutputObjectState buff = new OutputObjectState();
        final String tn = "/StateManager/junit";

        // add a record to the object store
        assertTrue(StoreManager.getRecoveryStore().write_committed(new Uid(), tn, buff));

        // validate that there was no change to the filesystem
        System.out.println("Checking that " + defaultStoreDir + " was not created by the test");
	//        assertFalse(new File(defaultStoreDir).exists());
    }

**Comment by nmcl** [comment]
TxStatsSystemErrorUnitTest ...

@Test
    public void test() throws Exception
    {
	if (true)
	    return;

**Comment by nmcl** [comment]
Won't fix as out of date.
